name : gredupedia
services:
 db:
  image: mysql:latest
  container_name: mysql
  ports:
   - "3306:3306"
  environment:
   - MYSQL_ROOT_PASSWORD=Gredupedia123
   - MYSQL_DATABASE=Gredupedia
  volumes:
   - C:/Users/user/Music/projek/Gredupedia-server/db:/var/lib/mysql